name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build IPA with Xcode-Builder Action
      uses: iOS-project-builder/action-ios-project-builder@v1
      with:
        project-path: Megaphone.xcodeproj
        scheme: Megaphone

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Megaphone-IPA
        path: "*.ipa"
