name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build App
      run: |
        xcodebuild -project Megaphone.xcodeproj -scheme Megaphone -sdk iphoneos -configuration Release CODE_SIGNING_ALLOWED=NO archive -archivePath $PWD/build/Megaphone.xcarchive
        
    - name: Create Payload and IPA
      run: |
        mkdir -p $PWD/build/Payload
        cp -r $PWD/build/Megaphone.xcarchive/Products/Applications/*.app $PWD/build/Payload/
        cd $PWD/build
        zip -r Megaphone.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Megaphone-IPA
        path: build/Megaphone.ipa
